version: '3.1'
services:
  javaapp:
    image: dependencycheck:1.0.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_HOST: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - db

  webapp:
    image: nginx:alpine
    build:
      context: ./User-Interface
    ports:
      - 80:80

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_HOST: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - ./mysql_scripts:/docker-entrypoint-initdb.d