spring:
    config:
        activate:
            on-profile: development
resources:
    db: H2
    logs: C:\temp\logs\
    secure: false
---
spring:
    config:
        activate:
            on-profile: production
resources:
    db: Oracle
    logs: //PROD_SERVER/logs/
    secure: true